
mission: "brain"
TAG: init

###### training configs ######
# val_index_class: ["bg", "NCR", "ED", "ET"]
# BraTS-GLI-T1C    # SSA | PED
#                  # T1C, T1N, T2F, T2W

infer_epoch_freq: 1  # 25
chunksize: 20

tr_domain: "BraTS-GLI-T1C"
te_domain: ["BraTS-SSA-T1C", "BraTS-PED-T1C"]

in_channel: 3     # 3 for 2D,
model_type: "3D"  # 2D | 3D | 2.5D

nclass: 4
fineSize: 128               # 192 original

contrast: True
sam: False

